# This is a basic workflow to help you get started with Actions

name: Python application - Postal Code (ZH)

on:
  schedule:
    - cron: 32 12 1 * *

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Check-out Repo
        uses: actions/checkout@master
        with:
          repository: ${{ secrets.repo }}
          token: ${{ secrets.htoken }}

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Set up OCR package
        run: |
          # install tesseract-ocr on linux
          sudo apt install tesseract-ocr
          sudo apt install libleptonica-dev
          sudo apt install libtesseract-dev

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          if [ -f eyes/requirements.txt ]; then pip install -r eyes/requirements.txt; fi

      - name: Grab data and upload
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cd eyes/
          d=`date +%Y-%m-%d`
          ${{secrets.CMD}} postal-code-zh -O zh-$d.json
          aws s3 cp zh-$d.json ${{ secrets.S3}}/postal-code/
