# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Nodejs application - Hot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2

      - name: Check-out Repo
        uses: actions/checkout@master
        with:
          repository: ${{ secrets.repo }}
          token: ${{ secrets.htoken }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: 'eyes/right-eye/Amaterasu'
      - run: pip install awscli
      - name: Grab data and upload
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          sudo timedatectl set-timezone Asia/Shanghai
          cd eyes/right-eye/Amaterasu
          npm install
          d=`date +%Y%m%d%H%M`
          node src/wbhot.js $d.json
          aws s3 cp $d.json ${{secrets.S3}}/webhot/